name: dle
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py36_0
  - asn1crypto=0.24.0=py36_0
  - astroid=2.2.5=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - babel=2.6.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36h7a1dbc1_1
  - chardet=3.0.4=py36_1
  - cloudpickle=0.8.0=py36_0
  - colorama=0.4.1=py36_0
  - cryptography=2.6.1=py36h7a1dbc1_0
  - cycler=0.10.0=py36h009560c_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.5.0=py36_1
  - docutils=0.14=py36h6012d8f_0
  - entrypoints=0.3=py36_0
  - freetype=2.8=h51f8f2c_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py36_0
  - imagesize=1.1.0=py36_0
  - intel-openmp=2019.3=203
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.4.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - isort=4.3.16=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.2.4=py36_0
  - jupyter_core=4.4.0=py36_0
  - keyring=18.0.0=py36_0
  - kiwisolver=1.0.1=py36h6538335_0
  - lazy-object-proxy=1.3.1=py36hfa6e2cd_2
  - libpng=1.6.36=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.0.10=hb898794_2
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=2.2.2=py36h153e9ff_1
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36he774522_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36hdbbee80_0
  - mkl_random=1.0.1=py36h77b88f5_1
  - more-itertools=6.0.0=py36_0
  - nbconvert=5.4.1=py36_3
  - nbformat=4.4.0=py36h3a5bc1b_0
  - nbstripout=0.3.5=py_0
  - ninja=1.9.0=py36h74a9793_0
  - notebook=5.2.2=py36hc48260a_0
  - numpy=1.13.3=py36h5c71026_4
  - numpydoc=0.8.0=py36_0
  - olefile=0.46=py36_0
  - openssl=1.1.1b=he774522_1
  - packaging=19.0=py36_0
  - pandas=0.21.1=py36h047fa9f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.4=py36_0
  - patsy=0.5.1=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=4.3.0=py36ha40f157_1
  - pip=19.0.3=py36_0
  - pluggy=0.9.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.1=py36he774522_0
  - py=1.8.0=py36_0
  - pycodestyle=2.5.0=py36_0
  - pycparser=2.19=py36_0
  - pyflakes=2.1.1=py36_0
  - pygments=2.3.1=py36_0
  - pylint=2.3.1=py36_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h6538335_2
  - pyrsistent=0.14.11=py36he774522_0
  - pysocks=1.6.8=py36_0
  - pytest=4.0.2=py36_0
  - python=3.6.7=h9f7ef89_2
  - python-dateutil=2.8.0=py36_0
  - pytorch=1.0.0=py3.6_cuda90_cudnn7_1
  - pytz=2018.9=py36_0
  - pywin32=223=py36hfa6e2cd_1
  - pyzmq=18.0.0=py36ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=0.5.7=py36_1
  - qtconsole=4.4.3=py36_0
  - qtpy=1.7.0=py36_1
  - requests=2.21.0=py36_0
  - rope=0.12.0=py36_0
  - scikit-learn=0.20.1=py36hb854c30_0
  - scipy=1.0.0=py36h1260518_0
  - seaborn=0.8.1=py36_0
  - setuptools=41.0.0=py36_0
  - sip=4.19.8=py36h6538335_0
  - six=1.12.0=py36_0
  - snowballstemmer=1.2.1=py36h763602f_0
  - sphinx=1.8.5=py36_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-websupport=1.1.0=py36_1
  - spyder=3.3.4=py36_0
  - spyder-kernels=0.4.4=py36_0
  - sqlite=3.27.2=he774522_0
  - statsmodels=0.9.0=py36h452e1ab_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hfa6e2cd_0
  - torchvision=0.2.1=py_2
  - traitlets=4.3.2=py36h096827d_0
  - typed-ast=1.3.1=py36he774522_0
  - urllib3=1.24.1=py36_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.1=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - wrapt=1.11.1=py36he774522_0
  - xz=5.2.4=h2fa13f4_4
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - alembic==1.0.8
    - configargparse==0.10.0
    - coverage==4.5.3
    - fuzzywuzzy==0.17.0
    - ipywidgets==7.4.2
    - jupyter==1.0.0
    - jupyter-console==6.0.0
    - mako==1.0.8
    - nbgrader==0.6.0.dev0
    - nbval==0.9.1
    - python-editor==1.0.4
    - sqlalchemy==1.3.2
    - tornado==4.5.3
    - widgetsnbextension==3.4.2
prefix: C:\Users\Zaguero\Anaconda3\envs\dle

